name: python-intro
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.6
  - jupyter
  - ipykernel
  - biopython
  - gseapy
  - pandas
  - scipy
  - numpy
  - seaborn
  - rise
  - tensorflow
  - pickle
  - os
  - cv2
  - PIL
  - imageio
  - random
  - sklearn
  - skimage
